accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('', views.profile, name='profile'),

    path('favorite_add/<slug:slug>/', views.add_to_favorite, name='add_to_favorite'),
    path('favorite_remove/<slug:slug>/', views.remove_from_favorite, name='remove_from_favorite'),
    path('favorite_remove-detail/<slug:slug>/', views.remove_from_favorite_detail, name='remove_from_favorite_detail'),
    path('favorite/', views.favorite_list, name='favorite_list'),


    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),

    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    # path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),

]

blog/urls.py
from django.urls import path
from .import views

app_name ='blog'

urlpatterns = [
    path('', views.blog_post_list, name='blog_post_list'),
    path('<slug:slug>/', views.blog_post_detail, name='blog_post_detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('add_cart_no_redirect/<int:product_id>/', views.add_cart_no_redirect, name='add_cart_no_redirect'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_no_redirect/<int:product_id>/<int:cart_item_id>/', views.remove_cart_no_redirect, name='remove_cart_no_redirect'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

york_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('shop/', include('store.urls', namespace='store')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from store.models import Product

# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')

        if not username:
            raise ValueError('User must have an username')

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user



class Account(AbstractBaseUser):
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    username        = models.CharField(max_length=50, unique=True)
    email           = models.EmailField(max_length=100, unique=True)
    phone_number    = models.CharField(max_length=50)

    # required
    date_joined     = models.DateTimeField(auto_now_add=True)
    last_login      = models.DateTimeField(auto_now_add=True)
    is_admin        = models.BooleanField(default=False)
    is_staff        = models.BooleanField(default=False)
    is_active        = models.BooleanField(default=False)
    is_superadmin        = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(blank=True, max_length=100)
    address_line_2 = models.CharField(blank=True, max_length=100)
    profile_picture = models.ImageField(blank=True, upload_to='userprofile')
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'



class Favorite(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

store/models.py
import os
from io import BytesIO
from ckeditor.fields import RichTextField
from django.core.files.base import ContentFile
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from store.utils import get_file_name
from category.models import Category
from PIL import Image


class Manufacturer(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to=get_file_name)
    grid_image = models.ImageField(upload_to=get_file_name, blank=True)
    position = models.PositiveIntegerField()
    is_visible = models.BooleanField(default=True)
    description = RichTextField()
    h1 = models.CharField(max_length=255, blank=True)
    meta_title = models.CharField(max_length=255, blank=True)
    meta_description = models.CharField(max_length=255, blank=True)

    def save(self, *args, **kwargs):
        # проверяем, есть ли изображение
        if self.image:
            # открываем изображение с помощью библиотеки PIL
            img = Image.open(self.image)

            # проверяем, является ли изображение квадратным
            if img.width != img.height:
                size = (max(img.width, img.height), max(img.width, img.height))
                img_with_border = Image.new("RGB", size, (245, 245, 245))
                x = (size[0] - img.width) // 2
                y = (size[1] - img.height) // 2
                img_with_border.paste(img, (x, y))

                # получаем формат изображения из имени файла
                file_ext = os.path.splitext(self.image.name)[1].lower()
                format_dict = {'.jpg': 'JPEG', '.jpeg': 'JPEG', '.png': 'PNG', '.gif': 'GIF'}
                image_format = format_dict.get(file_ext, 'JPEG')

                # сохраняем квадратное изображение в том же формате, что и оригинал
                img_io = BytesIO()
                img_with_border.save(img_io, format=image_format)
                img_io.seek(0)
                self.image.save(self.image.name, ContentFile(img_io.read()), save=False)

        super(Manufacturer, self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse("store:brand_detail", args=[self.slug])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to=get_file_name, blank=True)
    article = models.CharField(max_length=200, null=True, blank=True)
    barcode = models.DecimalField(max_digits=20, decimal_places=0, null=True, blank=True)
    description = models.TextField(blank=True)
    main_price = models.DecimalField(max_digits=10, decimal_places=2)
    discounted_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, null=True, blank=True)
    product_count = models.DecimalField(max_digits=10, decimal_places=0, null=True, blank=True)
    bags_in_case = models.DecimalField(max_digits=10, decimal_places=0, null=True, blank=True)
    weight = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    available_quantity = models.DecimalField(max_digits=10, decimal_places=0, null=True, blank=True)
    available = models.BooleanField(default=True)
    position = models.PositiveIntegerField(default=1)
    category = models.ManyToManyField(Category, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    STASTUS_CHOICES = [
        ('N', 'Out of Stock'),
        ('I', 'In stock'),
        ('S', 'Soon in stock'),
        ]
    status = models.CharField(max_length=1, choices=STASTUS_CHOICES, blank=True, default='N')

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def price(self):
        if self.discounted_price is None or self.discounted_price >= self.main_price:
            return self.main_price
        else:
            return self.discounted_price

    def save(self, *args, **kwargs):
        if self.image:
            # открываем изображение с помощью библиотеки PIL
            img = Image.open(self.image)

            # проверяем, является ли изображение квадратным
            if img.width != img.height:
                size = (max(img.width, img.height), max(img.width, img.height))
                img_with_border = Image.new("RGB", size, (255, 255, 255))
                x = (size[0] - img.width) // 2
                y = (size[1] - img.height) // 2
                img_with_border.paste(img, (x, y))

                # получаем формат изображения из имени файла
                file_ext = os.path.splitext(self.image.name)[1].lower()
                format_dict = {'.jpg': 'JPEG', '.jpeg': 'JPEG', '.png': 'PNG', '.gif': 'GIF'}
                image_format = format_dict.get(file_ext, 'JPEG')

                # сохраняем квадратное изображение в том же формате, что и оригинал
                img_io = BytesIO()
                img_with_border.save(img_io, format=image_format)
                img_io.seek(0)
                self.image.save(self.image.name, ContentFile(img_io.read()), save=False)

        super(Product, self).save(*args, **kwargs)




class Promo(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to=get_file_name, blank=True)
    products = models.ManyToManyField(Product, related_name='promos')
    position = models.PositiveIntegerField()
    is_visible = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('store:promo_detail', args=[self.slug])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Promo'
        verbose_name_plural = 'Promos'


class RecommendedProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    position = models.PositiveIntegerField()

    class Meta:
        ordering = ['position']
        verbose_name_plural = 'Recommended products'

    def __str__(self):
        return self.product.name

accounts/forms.py
from django import forms
from .models import Account, UserProfile


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email Address'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'phone_number')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ('address_line_1', 'address_line_2', 'city', 'state', 'country', 'profile_picture')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

templates/accounts/account_verification_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on below link to confirm your registration.
http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}

templates/accounts/favorite_list.html
{% extends 'main.html' %}

{% load static %}


{% block content %}

<div class="sg-page-content">

    <section class="sg-global-content">
        <div class="container">
            <div class="row">

                {% include 'includes/profile_sidebar.html' %}

                <div class="col-lg-9">
                      <div class="sg-table sa-box mb-3">
                          <form class="woocommerce-cart-form" action="#">
                              <table class="table">
                                  <thead>
                                      <tr>
                                          <th scope="col">Product</th>
                                          <th scope="col">Date</th>
                                          <th scope="col">Status</th>
                                          <th scope="col">Total</th>
                                          <th scope="col">Action</th>
                                          <th scope="col">Delete item</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                    {% for item in favorites %}
                                        <tr>
                                            <th scope="row">
                                                <div class="product">
                                                    <a href="{{ item.product.get_absolute_url  }}">
                                                        <span class="product-thumb">
                                                            <img src="{{item.product.image.url}}" alt="Image" class="img-fluid">
                                                        </span>
                                                        <div class="text">
                                                            <p>{{ item.product.name }}</p>
                                                        </div>
                                                    </a>
                                                </div><!-- /.product -->
                                            </th>
                                            <td>{{item.created_at}}</td>
                                            <td>
                                                <div class="complete">
                                                    <span>{{ item.product.get_status_display }}</span>
                                                </div>
                                            </td>
                                            <td>
                                              {% if item.product.price == item.product.main_price %}
                                                <span>${{ item.product.price }}</span>
                                              {% else %}
                                                <span>
                                                  ${{ item.product.discounted_price }}
                                                  <del style="color: red;">{{ item.product.main_price }}</del>
                                                  </span>
                                              {% endif %}
                                            </td>
                                            <td>
                                                <div class="add-to-cart">
                                                  {% if item.product.id in product_ids_in_cart %}

                                                  <a href='{% url "cart:add_cart_no_redirect" item.product.id %}' style="background-color: green; color: white;" class="btn">
                                                      <span class="fas fa-check"></span>In cart
                                                  </a>
                                                  {% else %}

                                                    <a href='{% url "cart:add_cart_no_redirect" item.product.id %}' class="btn">Add to cart</a>
                                                  {% endif %}
                                                </div>
                                            </td>
                                            <td>
                                                <div class="delete">
                                            <a href="{% url 'accounts:remove_from_favorite' item.product.slug %}" onclick="return confirm('Are you sure you want to delete this item?')" class="btn btn-danger"> Remove</a>
                                              </div>
                                          </td>
                                      </tr>

                                        {% endfor %}

                                  </tbody>
                              </table>
                          </form>

                          <!-- <div class="show-more mt-4">
                              <a href="#" class="btn btn-primary">Show more</a>
                          </div> -->

                      </div>
                  </div>


            </div><!-- /.row -->
        </div><!-- /.container -->
    </section><!-- /.profile-section -->

</div><!-- /.sg-page-content -->

{% endblock %}

templates/accounts/forgotPassword.html
{% extends 'main.html' %}

{% load static %}


{% block content %}

<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->



	<div class="card mx-auto" style="max-width: 600px; margin-top:100px;">

      <div class="card-body">
      <h4 class="card-title mb-4">Forgot Password</h4>
      {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:forgotPassword' %}" method="POST">
        {% csrf_token %}
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email">
          </div> <!-- form-group// -->

          <div class="form-group">
          	<a href="{% url 'accounts:login' %}" class="float-right">Got password? Login</a>
            <br/>
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
          </div> <!-- form-group// -->
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->

</section>
{% endblock %}

templates/accounts/login.html
{% extends 'main.html' %}

{% load static %}


{% block content %}

<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->

{% if request.GET.command == 'verification' %}

<div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
Thank you for registering with us. We have sent you a verification email to your email address
<br><br>
Already verified? <a href="{% url 'accounts:login' %}">Login</a>
</div>

{% else %}

	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">

      <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
      {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email">
          </div> <!-- form-group// -->
          <div class="form-group">
			<input type="password" class="form-control" placeholder="Password" name="password">
          </div> <!-- form-group// -->

          <div class="form-group">
          	<a href="{% url 'accounts:forgotPassword' %}" class="float-right">Forgot password?</a>
						<br/>
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Login  </button>
          </div> <!-- form-group// -->
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->
{% endif %}

</section>
{% endblock %}

templates/accounts/my_orders.html
{% extends 'main.html' %}

{% load static %}


{% block content %}



<div class="sg-page-content">

    <section class="sg-global-content mb-3">
        <div class="container">
            <div class="row">

                {% include 'includes/profile_sidebar.html' %}

                <div class="col-lg-9">
                    <div class="sg-table sa-box">
                        <div class="title justify-content-between">
                            <h1>Order History</h1>
                        </div>
                        <form class="woocommerce-cart-form" action="#">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Order №</th>
                                        <th scope="col">Date</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Phone</th>
                                        <th scope="col">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  {% for order in orders %}
                                      <tr>
                                          <th scope="row">
                                              <div class="product">
                                                  <a href="{% url 'accounts:order_detail' order.order_number %}">
                                                    <span class="product-thumb">
                                                        <i class="fa-solid fa-cart-flatbed-suitcase"></i>
                                                    </span>
                                                      <div class="text">
                                                          <p> {{order.order_number}}</p>
                                                      </div>
                                                  </a>
                                              </div><!-- /.product -->
                                          </th>
                                          <td>{{order.created_at}}</td>
                                          <td>{{order.full_name}}</td>
                                          <td>{{order.phone}}</td>
                                          <td><span>${{order.order_total}}</span></td>
                                      </tr>
                                    {% endfor %}


                                </tbody>
                            </table>
                        </form>
                        <div class="show-more mt-4">
                            <a href="#" class="btn btn-primary">Show more</a>
                        </div>
                    </div>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section><!-- /.profile-section -->

</div><!-- /.sg-page-content -->

{% endblock %}

templates/accounts/register.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

<section class="section-content padding-y">

<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body">
        {% include 'includes/alerts.html' %}
		<header class="mb-4"><h4 class="card-title">Sign up</h4></header>
		<form action="{% url 'accounts:register' %}" method="POST">
      {% csrf_token %}


				<div class="form-row">
					<div class="col form-group">
						<label>First name</label>
					  	{{ form.first_name }}
					</div> <!-- form-group end.// -->
					<div class="col form-group">
						<label>Last name</label>
					  	{{ form.last_name }}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row end.// -->


				<div class="form-row">
					<div class="form-group col-md-6">
					  <label>Email Address</label>
					  {{form.email}}
					</div> <!-- form-group end.// -->
					<div class="form-group col-md-6">
					  <label>Phone Number</label>
					  {{form.phone_number}}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row.// -->
				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Create password</label>
					    {{ form.password }}
					</div> <!-- form-group end.// -->
					<div class="form-group col-md-6">
						<label>Repeat password</label>
            {{form.confirm_password}}
					</div> <!-- form-group end.// -->
				</div>
			    <div class="form-group">
			        <button type="submit" class="btn btn-primary btn-block"> Register  </button>
			    </div> <!-- form-group// -->
      {{ form.email.errors }}
      {{ form.non_field_errors }}
			</form>
		</article><!-- card-body.// -->
    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
    <br><br>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>


{% endblock %}

templates/accounts/resetPassword.html
{% extends 'main.html' %}


{% block content %}

<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->



	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">

      <div class="card-body">
      <h4 class="card-title mb-4">Reset Password</h4>
      {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:resetPassword' %}" method="POST">
        {% csrf_token %}
          <div class="form-group">
			 <input type="password" class="form-control" placeholder="Create Password" name="password">
          </div> <!-- form-group// -->
          <div class="form-group">
			<input type="password" class="form-control" placeholder="Confirm Password" name="confirm_password">
          </div> <!-- form-group// -->


          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Reset  </button>
          </div> <!-- form-group// -->
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name}},

As requested, please click below link to reset your password.
http://{{domain}}{% url 'accounts:resetpassword_validate' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}