accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('', views.profile, name='profile'),

    path('favorite_add/<slug:slug>/', views.add_to_favorite, name='add_to_favorite'),
    path('favorite_remove/<slug:slug>/', views.remove_from_favorite, name='remove_from_favorite'),
    path('favorite_remove-detail/<slug:slug>/', views.remove_from_favorite_detail, name='remove_from_favorite_detail'),
    path('favorite/', views.favorite_list, name='favorite_list'),


    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),

    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    # path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),

]

blog/urls.py
from django.urls import path
from .import views

app_name ='blog'

urlpatterns = [
    path('', views.blog_post_list, name='blog_post_list'),
    path('<slug:slug>/', views.blog_post_detail, name='blog_post_detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('add_cart_no_redirect/<int:product_id>/', views.add_cart_no_redirect, name='add_cart_no_redirect'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_no_redirect/<int:product_id>/<int:cart_item_id>/', views.remove_cart_no_redirect, name='remove_cart_no_redirect'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

store/urls.py
from django.urls import path
from .views import product_list, product_detail, category_list, all_product_list, search, brands, brand_detail, promo_list, promo_detail

app_name = 'store'

urlpatterns = [
    path('promo/', promo_list, name='promo_list'),
    path('promo/<slug:slug>/', promo_detail, name='promo_detail'),
    path('brands/', brands, name='brands'),
    path('brands/<slug:slug>/', brand_detail, name='brand_detail'),
    path('search/', search, name='search'),
    path('category/', category_list, name='category_list'),
    path('category/<slug:slug>/', product_list, name='product_list'),
    path('<slug:slug>/', product_detail, name='product_detail'),
    path('', all_product_list, name='all_product_list'),




]

york_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('shop/', include('store.urls', namespace='store')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/alerts.html
{% if messages %}

    {% for message in messages %}
    <div id="message" class="container">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
    </div>
    </div>
    {% endfor %}

{% endif %}

templates/includes/baner_main_up_discount.html
<div class="popup-modal modal fade" tabindex="-1" id="sg-modal">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-6">
                        <img src="images/product/modal.png" alt="Image" class="img-fluid">
                    </div>
                    <div class="col-lg-6">
                        <h2>Get <span>25%</span> Discount</h2>
                        <p>Subscribe to the yoori shop newsletter to receive updates on special offers.</p>
                        <form action="#">
                            <div class="form-group">
                                <input type="email" class="form-control" required="required" placeholder="Email Address">
                            </div>
                            <button class="btn btn-primary text-uppercase" name="submit" type="submit">Subscribe</button>
                        </form>
                        <div class="social">
                            <ul class="global-list">
                                <li><a href="#"><span><i class="fa-brands fa-facebook"></i></span></a></li>
                                <li><a href="#"><span><i class="fa-brands fa-twitter"></i></span></a></li>
                                <li><a href="#"><span><i class="fa-brands fa-linkedin"></i></span></a></li>
                                <li><a href="#"><span><i class="fa-brands fa-instagram"></i></span></a></li>
                                <li><a href="#"><span><i class="fa-brands fa-pinterest"></i></span></a></li>
                            </ul>
                        </div>
                        <div class="form-group tnc">
                            <input type="checkbox" name="tnc" id="tnc">
                            <label for="tnc">Don't show this popup again</label>
                        </div>
                    </div>
                </div><!-- /.row -->
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/includes/footer.html
{% load static %}

<footer class="footer-section">
    <div class="container">
        <div class="footer-top">
            <div class="row">
                <div class="col-md-6 col-lg-3">
                    <div class="footer-widget">
                        <h3>About</h3>
                        <p>York Snack Food Distr. Inc., based in Philadelphia, Pennsylvania, has been a key player in the U.S. snack market for over 20 years. Specializing in chips, snacks, and candy, the company distributes popular brands such as Wise, Frito Lay, Utz, Mr. G, Rap Snack, and Andy Capp's.</p>
                        <div class="social">
                            <ul class="global-list">
                                <li><a href="#"><span><i class="fa-brands fa-facebook"></i></span></a></li>
                                <li><a href="#"><span><i class="fa-brands fa-twitter"></i></span></a></li>
                                <li><a href="#"><span><i class="fa-brands fa-linkedin"></i></span></a></li>
                                <li><a href="#"><span><i class="fa-brands fa-instagram"></i></span></a></li>
                                <li><a href="#"><span><i class="fa-brands fa-pinterest"></i></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-2">
                    <div class="footer-widget">
                        <h3>Useful Links</h3>
                        <ul class="global-list">
                            <li><a href="{% url 'home' %}">Home</a></li>
                            <li><a href="{% url 'store:category_list' %}">All Categories</a></li>
                            <li><a href="{% url 'store:brands' %}">All Brands</a></li>
                            <li><a href="{% url 'store:all_product_list' %}">All Products</a></li>
                            <li><a href="{% url 'delivery' %}">Delivery</a></li>
                            <li><a href="{% url 'payment' %}">Payment</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 col-lg-2">
                    <div class="footer-widget">
                        <h3>My Account</h3>
                        <ul class="global-list">
                            <li><a href="#">Login</a></li>
                            <li><a href="#">Purchase History</a></li>
                            <li><a href="#">My Wishlist</a></li>
                            <li><a href="#">Track Order</a></li>
                            <li><a href="#">My Account</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="footer-widget">
                        <h3>Contact Us</h3>
                        <div class="address">
                            <ul class="global-list">
                               <li>
                                    <h4><span><i class="fa-solid fa-house"></i></span>Address</h4>
                                    <p>{{contacts.address}}</p>
                               </li>
                               <li>
                                    <h4><span><i class="fa-solid fa-envelope"></i></span>Email</h4>
                                    <a href="#">{{contacts.email}}</a>
                               </li>
                               <li>
                                    <h4><span><i class="fa-solid fa-phone"></i></span>Phone</h4>
                                    <a href="tel:{{contacts.phone_1}}">{{contacts.phone_1}}</a>
                               </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-2">
                    <div class="footer-widget">
                        <h3>For partners</h3>
                        <ul class="global-list">
                            <li><a href="#">Cooperation</a></li>

                        </ul>
                    </div>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.footer-top -->

    <div class="footer-bottom">
        <div class="container">
            <div class="footer-bottom-content">
                <div class="copyright">
                    <p>Copyright &copy; 2024 York Snack Food Distribution Inc - All Rights Reserved.</p>
                    <p>Developer by shamansk1y</p>
                </div>
            </div>
        </div><!-- /.container -->
    </div><!-- /.footer-bottom -->
</footer><!-- /.footer-section -->

templates/includes/hiro.html
{% load static %}

<div class="hero-section">
    <div class="hero-content">
        <div id="hero-slider" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for item in slider %}
                    <div class="carousel-item{% if forloop.first %} active{% endif %}" style="background-image: url({{ item.image_bg.url }});">
                        <div class="container">
                            <div class="item-content">
                                <div class="row">
                                    <div class="col-md-4 order-md-last">
                                        <div class="thumb animated slideInUp">
                                            <img src="{{ item.image.url }}" alt="Image" class="img-fluid">
                                        </div>
                                    </div>
                                    <div class="col-md-8 align-self-center">
                                        <div class="hero-text">
                                            <h2 class="animated slideInUp">{{ item.h_1 }}</h2>
                                            <h3 class="animated slideInUp">{{ item.desc }}</h3>
                                            <a href="{{ item.tab_url }}" class="btn btn-primary animated slideInUp">{{ item.tab }} <span class="fa-solid fa-arrow-right"></span></a>
                                        </div>
                                    </div>
                                </div><!-- /.row -->
                            </div><!-- /.item-content -->
                        </div><!-- /.container -->
                    </div>
                {% endfor %}
            </div>

            <ol class="carousel-indicators">
                {% for item in slider %}
                    <li data-bs-target="#hero-slider" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
                {% endfor %}
            </ol>

        </div><!-- /.hero-content -->
    </div><!-- /.hero-content -->
</div><!-- /.hero-section -->

templates/includes/last_added_product.html
<section class="products-section">
    <div class="container">
        <div class="sa-box">
            <div class="title justify-content-between">
                <h1>New products</h1>
            </div>
            <ul class="products grid-6">
                {% for product in last_products %}
                    <li>
                        {% include 'includes/product_card_in_list.html' %}
                    </li>
                {% endfor %}
            </ul>
        </div><!-- /.sa-box -->
    </div><!-- /.container -->
</section>

templates/includes/manufacturer_main_page.html
<section class="product-section p-0">
    <div class="container">
        <div class="sa-box">
            <div class="title justify-content-between">
                <h1>Brands</h1>
            </div>

            <div class="recent-product-slider">
                {% for brand in brands %}
                    <div class="recent-product">
                        <div class="product-thumb">
                            <a href="{% url 'store:brand_detail' slug=brand.slug %}"><img src="{{ brand.image.url }}" alt="Image" class="img-fluid"></a>
                        </div>
                        <div class="overlay">
                            <h2><a href="{% url 'store:brand_detail' slug=brand.slug %}"><i class="fa-solid fa-link"></i></a></h2>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div><!-- /.sa-box -->
    </div><!-- /.container -->
</section><!-- /.product-section -->

templates/includes/product_card_in_list.html
<div class="sg-product">
    <div class="product-thumb">
        <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt="Image" class="img-fluid"></a>
    </div>
    <div class="product-info">
      {% if product.price == product.main_price %}
        <span class="price"> ${{ product.main_price }}</span>
      {% else %}
        <span class="price"><del>${{ product.main_price }}</del> ${{ product.discounted_price }}</span>
      {% endif %}

        <h3>
          <a href="{{ product.get_absolute_url }}" style="display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 100%;">
              {{ product.name }}
          </a>
        </h3>
        <div class="icons">
            <ul class="global-list">
                <li><a href="{% url 'cart:add_cart' product.id %}"><span><i class="fas fa-cart-plus"></i></span></a></li>
                <li><a href="{{ product.get_absolute_url }}"><span><i class="far fa-eye"></i></span></a></li>
                <!-- <li><a href="#"><span><i class="far fa-heart"></i></span></a></li> -->
            </ul>
        </div>
    </div>
    <div class="button-wrapper">
        <button class="btn btn-secondary" onclick="location.href='{{ product.get_absolute_url }}'">View</button>
        {% if product.id in product_ids_in_cart %}
          <a href="#" class="btn btn-success"><span class="fas fa-check"></span>Added to cart</a>
        {% else %}
          <button class="btn btn-warning btn-medium btn-round btn-icon" onclick="location.href='{% url 'cart:add_cart' product.id %}'">Add to cart</button>
        {% endif %}
    </div>
    <br/>
</div><!-- /.sg-product -->

templates/includes/profile_sidebar.html
<div class="col-lg-3">
    <div class="sidebar-menu">
        <ul class="global-list">
            <li class="active"><a href="{% url "accounts:profile" %}"><span><i class="fa-regular fa-user"></i></span> My Profile</a></li>
            <!-- <li><a href="{% url "accounts:edit_profile" %}"><span><i class="fa-regular fa-pen-to-square"></i></span> Edit Profile</a></li> -->
            <li><a href="{% url "accounts:favorite_list" %}"><span><i class="fa-regular fa-heart"></i></span> Wishlist</a></li>
            <li><a href="{% url "accounts:my_orders" %}"><span><i class="fa-solid fa-cart-flatbed-suitcase"></i></span> Order History</a></li>
            <!-- <li><a href="change-password.html"><span><i class="fa-solid fa-lock"></i></span> Change Password</a></li> -->
            <li><a href="#"><span><i class="fa-solid fa-arrow-right-from-bracket"></i></span> Logout</a></li>
        </ul>
    </div>
</div>

templates/includes/recommended_product.html
<section class="products-section">
    <div class="container">
        <div class="sa-box">
            <div class="title justify-content-between">
                <h1>Recommended products</h1>
            </div>
            <ul class="products grid-6">
                {% for item in recommended_products %}
                    <li>
                      <div class="sg-product">
                          <div class="product-thumb">
                              <a href="{{ item.product.get_absolute_url }}"><img src="{{ item.product.image.url }}" alt="Image" class="img-fluid"></a>
                          </div>
                          <div class="product-info">
                            {% if item.product.price == item.product.main_price %}
                              <span class="price"> ${{ item.product.main_price }}</span>
                            {% else %}
                              <span class="price"><del>${{ item.product.main_price }}</del> ${{ item.product.discounted_price }}</span>
                            {% endif %}

                              <h3>
                                <a href="{{ product.get_absolute_url }}" style="display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 100%;">
                                    {{ item.product.name }}
                                </a>
                              </h3>
                              <div class="icons">
                                  <ul class="global-list">
                                      <li><a href="{% url 'cart:add_cart' item.product.id %}"><span><i class="fas fa-cart-plus"></i></span></a></li>
                                      <li><a href="{{ item.product.get_absolute_url }}"><span><i class="far fa-eye"></i></span></a></li>
                                      <!-- <li><a href="#"><span><i class="far fa-heart"></i></span></a></li> -->
                                  </ul>
                              </div>
                          </div>
                          <div class="button-wrapper">
                              <button class="btn btn-secondary" onclick="location.href='{{ item.product.get_absolute_url }}'">View</button>
                              {% if item.product.id in product_ids_in_cart %}
                                <a href="#" class="btn btn-success"><span class="fas fa-check"></span>Added to cart</a>
                              {% else %}
                                <button class="btn btn-warning btn-medium btn-round btn-icon" onclick="location.href='{% url 'cart:add_cart' item.product.id %}'">Add to cart</button>
                              {% endif %}
                          </div>
                          <br/>
                      </div><!-- /.sg-product -->
                    </li>
                {% endfor %}
            </ul>
        </div><!-- /.sa-box -->
    </div><!-- /.container -->
</section>