blog/urls.py
from django.urls import path
from .import views

app_name ='blog'

urlpatterns = [
    path('', views.blog_post_list, name='blog_post_list'),
    path('<slug:slug>/', views.blog_post_detail, name='blog_post_detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('add_cart_no_redirect/<int:product_id>/', views.add_cart_no_redirect, name='add_cart_no_redirect'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_no_redirect/<int:product_id>/<int:cart_item_id>/', views.remove_cart_no_redirect, name='remove_cart_no_redirect'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

store/urls.py
from django.urls import path
from .views import product_list, product_detail, category_list, all_product_list, search, brands, brand_detail, promo_list, promo_detail

app_name = 'store'

urlpatterns = [
    path('promo/', promo_list, name='promo_list'),
    path('promo/<slug:slug>/', promo_detail, name='promo_detail'),
    path('brands/', brands, name='brands'),
    path('brands/<slug:slug>/', brand_detail, name='brand_detail'),
    path('search/', search, name='search'),
    path('category/', category_list, name='category_list'),
    path('category/<slug:slug>/', product_list, name='product_list'),
    path('<slug:slug>/', product_detail, name='product_detail'),
    path('', all_product_list, name='all_product_list'),




]

york_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('shop/', include('store.urls', namespace='store')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

carts/models.py
from django.db import models
from store.models import Product
from accounts.models import Account


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price() * self.quantity

    def __unicode__(self):
        return self.product

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from main_page.context_data import get_common_context, get_page_context



def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)  # Get the product

    # If the user is authenticated
    if current_user.is_authenticated:
        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.get(product=product, user=current_user)
            cart_item.quantity += 1
            cart_item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user,
            )
            cart_item.save()
        return redirect('cart:cart')

    # If the user is not authenticated
    else:
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))  # Get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.get(product=product, cart=cart)
            cart_item.quantity += 1
            cart_item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            cart_item.save()
        return redirect('cart:cart')



def add_cart_no_redirect(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)  # Get the product

    # If the user is authenticated
    if current_user.is_authenticated:
        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.get(product=product, user=current_user)
            cart_item.quantity += 1
            cart_item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user,
            )
            cart_item.save()
        return redirect(request.META.get('HTTP_REFERER'))

    # If the user is not authenticated
    else:
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))  # Get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.get(product=product, cart=cart)
            cart_item.quantity += 1
            cart_item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            cart_item.save()
        return redirect(request.META.get('HTTP_REFERER'))



def remove_cart_no_redirect(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect(request.META.get('HTTP_REFERER'))

def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart:cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart:cart')

def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            item_total = cart_item.product.price() * cart_item.quantity
            cart_item.item_total = item_total  # Add item_total attribute to cart_item
            total += item_total
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        # do not use tax
        tax = 0
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass  # Just ignore


    data = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    context_req = get_page_context(request)
    data.update(context_req)
    context_data = get_common_context()
    data.update(context_data)
    return render(request, 'carts/cart.html', context=data)

@login_required(login_url='accounts:login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            item_total = cart_item.product.price() * cart_item.quantity
            cart_item.item_total = item_total  # Add item_total attribute to cart_item
            total += item_total
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        # do not use tax
        tax = 0
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass  # Just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/checkout.html', context)

templates/carts/cart.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

<div class="sg-page-content">
<div class="sg-breadcrumb">
    <div class="container">
        <ol class="breadcrumb justify-content-center">
            <li class="breadcrumb-item">View Cart</li>
            <li class="breadcrumb-item"><a href="{% url 'cart:checkout' %}">Check Out</a></li>
            <li class="breadcrumb-item"><a href="#">Confirm Order</a></li>
        </ol>
    </div>
</div><!-- /.sg-breadcrumb -->

<section class="sg-global-content pt-0 mb-3">
    <div class="container">
      {% if not cart_items %}
            <h2 class="text-center">Your Shopping Cart is Empty</h2>
            <br>
            <div class="text-center">
                <a href="{% url 'store:all_product_list' %}" class="btn btn-primary">Continue Shopping</a>
            </div>
        {% else %}
        <div class="row">
            <div class="col-lg-8">
                <div class="sg-table sa-box">
                    <form class="woocommerce-cart-form" action="#">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Product</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Total</th>
                                    <th scope="col">Delete item</th>
                                </tr>
                            </thead>
                            <tbody>

                              {% for cart_item in cart_items %}
                                <tr>
                                    <th scope="row">
                                        <div class="product">
                                            <a href="{{ cart_item.product.get_absolute_url }}">
                                                <span class="product-thumb">
                                                    <img src="{{ cart_item.product.image.url }}" alt="Image" class="img-fluid">
                                                </span>
                                                <div class="text">
                                                    <p>{{ cart_item.product.name }}</p>
                                                    <span>SKU: {{ cart_item.product.article }}</span>
                                                    <span>Bags in case: {{ cart_item.product.bags_in_case }},</span>
                                                    <span>Brand: {{ cart_item.product.manufacturer }}</span>
                                                </div>
                                            </a>
                                        </div><!-- /.product -->
                                    </th>
                                    <td>
                                        <div class="product-quantity">
                                            <div class="quantity" data-trigger="spinner">
                                                <a href="{% url 'cart:remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                                <input type="text" name="quantity" value="{{ cart_item.quantity }}" title="quantity" class="input-text">
                                                <a href="{% url 'cart:add_cart' cart_item.product.id  %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-plus"></i> </a>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                      <div class="price-wrap">
                                        {% if cart_item.product.price == cart_item.product.main_price %}
                                            <span class="price">$ {{ cart_item.product.price }} each</span>
                                        {% else %}
                                            <span class="price">$ {{ cart_item.product.price }} each <del>${{ cart_item.product.main_price }}</del></span>
                                        {% endif %}
                                    </div> <!-- price-wrap .// --></td>

                                    <td>
                                      <div class="price-wrap">
                                      <span class="price">{{ cart_item.item_total }}</span>
                                    </div> <!-- price-wrap .// --></td>

                                    <td>
                                        <div class="delete">
                                            <a href="{% url 'cart:remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure you want to delete this item?')" class="btn btn-danger"> Remove</a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
            <div class="col-lg-4 pl-lg-5">
                <div class="order-summary sa-box">
                    <h6>Price Details</h6>
                    <div class="sg-card">
                        <ul class="global-list">
                            <li>Subtotal <span>${{total}}</span></li>
                            <!-- <li>Tax <span>${{tax}}</span></li> -->
                        </ul>
                        <div class="order-total">
                            <p>Total <span>${{grand_total}}</span></p>
                        </div>
                        <a href="{% url 'cart:checkout' %}" class="btn btn-primary">Checkout</a>
                    </div>
                </div>
            </div>
        </div><!-- /.row -->
        {% endif %}
    </div>
</section><!-- /.shopping-cart -->

</div><!-- /.sg-page-content -->

{% endblock %}