blog/urls.py
from django.urls import path
from .import views

app_name ='blog'

urlpatterns = [
    path('', views.blog_post_list, name='blog_post_list'),
    path('<slug:slug>/', views.blog_post_detail, name='blog_post_detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('add_cart_no_redirect/<int:product_id>/', views.add_cart_no_redirect, name='add_cart_no_redirect'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_no_redirect/<int:product_id>/<int:cart_item_id>/', views.remove_cart_no_redirect, name='remove_cart_no_redirect'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),

]

store/urls.py
from django.urls import path
from .views import product_list, product_detail, category_list, all_product_list, search, brands, brand_detail, promo_list, promo_detail

app_name = 'store'

urlpatterns = [
    path('promo/', promo_list, name='promo_list'),
    path('promo/<slug:slug>/', promo_detail, name='promo_detail'),
    path('brands/', brands, name='brands'),
    path('brands/<slug:slug>/', brand_detail, name='brand_detail'),
    path('search/', search, name='search'),
    path('category/', category_list, name='category_list'),
    path('category/<slug:slug>/', product_list, name='product_list'),
    path('<slug:slug>/', product_detail, name='product_detail'),
    path('', all_product_list, name='all_product_list'),




]

york_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('shop/', include('store.urls', namespace='store')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/views.py
from django.shortcuts import get_object_or_404, render, redirect
from main_page.context_data import get_common_context, get_page_context
from main_page.views import handle_post_request
from .models import Product, Manufacturer, Promo
from category.models import Category
from carts.models import CartItem, Cart
from carts.views import _cart_id
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from accounts.models import Favorite
from decimal import Decimal




def product_list(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(category=category, available=True)

    # Получаем уникальные значения только для текущей категории
    weights = products.values_list('weight', flat=True).distinct().order_by('weight')
    bags_in_case = products.values_list('bags_in_case', flat=True).distinct().order_by('bags_in_case')
    manufacturers_cat = Manufacturer.objects.filter(product__category=category).distinct()

    manufacturer_filter = request.GET.get('manufacturer', '')
    weight_filter = request.GET.get('weight', '')
    bags_filter = request.GET.get('bags', '')

    # Обрабатываем manufacturer_filter как строку с разделением по запятым
    manufacturer_filters = []
    if manufacturer_filter:
        manufacturer_filters = [int(m) for m in manufacturer_filter.split(',')]
        products = products.filter(manufacturer__id__in=manufacturer_filters)

    # Обрабатываем weight_filter
    weight_filters = []
    if weight_filter:
        weight_filters = [Decimal(w) for w in weight_filter.split(',')]
        products = products.filter(weight__in=weight_filters)

    # Обрабатываем bags_filter
    bags_filters = []
    if bags_filter:
        bags_filters = [int(b) for b in bags_filter.split(',')]
        products = products.filter(bags_in_case__in=bags_filters)

    data = {
        'page_products': products,
        'category': category,
        'manufacturers_cat': manufacturers_cat,
        'manufacturer_filters': manufacturer_filters,
        'weight_filters': weight_filters,
        'bags_filters': bags_filters,
        'weights': weights,
        'bags_in_case': bags_in_case,
    }

    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)

    return render(request, 'product_list.html', context=data)



def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    cart_id = _cart_id(request)
    item_in_cart = False
    if request.user.is_authenticated:
        favorites = Favorite.objects.filter(user=request.user)
    else:
        favorites = None
    user_favorites = []
    if request.user.is_authenticated:
        user_favorites = Favorite.objects.filter(user=request.user, product=product)

    try:
        cart = Cart.objects.get(cart_id=cart_id)
        item_in_cart = CartItem.objects.filter(product=product, cart=cart).exists()
    except Cart.DoesNotExist:
        cart = None

    discount_amount = None
    discount_percentage = None
    # Calculate discount and percentage
    if product.discounted_price is not None:
        discount_amount = product.main_price - product.discounted_price
        discount_percentage = round((discount_amount / product.main_price) * 100, 2)

    # Get similar items, check if category exists
    if product.category.exists():  # Убедитесь, что категория существует
        category = product.category.first()  # Получаем первую категорию (если их несколько)
        similar_items = Product.objects.filter(category=category).exclude(id=product.id)
        similar_items_count = similar_items.count()

        # If less than 4 items, take all, otherwise select 4 random
        if similar_items_count < 4:
            similar_items = similar_items
        else:
            similar_items = similar_items.order_by('?')[:4]
    else:
        similar_items = []  # Если категории нет, просто не показывать похожие товары

    context = {
        'product': product,
        'item_in_cart': item_in_cart,
        'discount_amount': discount_amount,
        'discount_percentage': discount_percentage,
        'similar_items': similar_items,
        'favorites': favorites,
        'user_favorites': user_favorites,

    }

    if request.method == 'POST':
        if not cart:
            cart = Cart.objects.create(cart_id=cart_id)

        try:
            cart_item = CartItem.objects.get(product=product, cart=cart)
            cart_item.quantity += 1
            cart_item.save()
        except CartItem.DoesNotExist:
            cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        return redirect('store:product_detail', slug=slug)

    context_req = get_page_context(request)
    context_data = get_common_context()
    context.update(context_data)
    context.update(context_req)
    return render(request, 'details.html', context=context)


def category_list(request):
    if request.method == 'POST':
        handle_post_request(request)

    categories = Category.objects.all()
    data = {
        'categories': categories,
    }
    return render(request, 'category_list.html', context=data)


def all_product_list(request):
    products = Product.objects.filter(available=True).order_by('position')

    # Получаем уникальные значения только для текущей категории
    weights = products.values_list('weight', flat=True).distinct().order_by('weight')
    bags_in_case = products.values_list('bags_in_case', flat=True).distinct().order_by('bags_in_case')
    manufacturers_cat = Manufacturer.objects.filter(is_visible=True).distinct()

    manufacturer_filter = request.GET.get('manufacturer', '')
    weight_filter = request.GET.get('weight', '')
    bags_filter = request.GET.get('bags', '')

    # Обрабатываем manufacturer_filter как строку с разделением по запятым
    manufacturer_filters = []
    if manufacturer_filter:
        manufacturer_filters = [int(m) for m in manufacturer_filter.split(',')]
        products = products.filter(manufacturer__id__in=manufacturer_filters)

    # Обрабатываем weight_filter
    weight_filters = []
    if weight_filter:
        weight_filters = [Decimal(w) for w in weight_filter.split(',')]
        products = products.filter(weight__in=weight_filters)

    # Обрабатываем bags_filter
    bags_filters = []
    if bags_filter:
        bags_filters = [int(b) for b in bags_filter.split(',')]
        products = products.filter(bags_in_case__in=bags_filters)

    data = {
        'page_products': products,
        'manufacturers_cat': manufacturers_cat,
        'manufacturer_filters': manufacturer_filters,
        'weight_filters': weight_filters,
        'bags_filters': bags_filters,
        'weights': weights,
        'bags_in_case': bags_in_case,
    }
    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)
    return render(request, 'product_list.html', context=data)


def search(request):
    products = []
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created').filter(Q(description__icontains=keyword) | Q(name__icontains=keyword))

    data = {
        'page_products': products,
    }
    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)
    return render(request, 'search_product_list.html', context=data)


def brands(request):
    brands = Manufacturer.objects.filter(is_visible=True)
    data = {
        'brands': brands,
    }
    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)
    return render(request, 'store/brands.html', context=data)


def brand_detail(request, slug):
    brand = get_object_or_404(Manufacturer, slug=slug)
    context = {
        'brand': brand,
    }

    context_req = get_page_context(request)
    context_data = get_common_context()
    context.update(context_data)
    context.update(context_req)
    return render(request, 'store/brand_single.html', context=context)


def promo_list(request):
    promos = Promo.objects.filter(is_visible=True)
    context = {
        'promos': promos,
    }
    context_req = get_page_context(request)
    context_data = get_common_context()
    context.update(context_data)
    context.update(context_req)
    return render(request, 'store/promo_list.html', context=context)


def promo_detail(request, slug):
    promo = get_object_or_404(Promo, slug=slug)
    products = promo.products.all()
    context = {
        'products': products,
    }
    context_req = get_page_context(request)
    context_data = get_common_context()
    context.update(context_data)
    context.update(context_req)
    return render(request, 'store/promo_detail.html', context=context)

templates/store/brand_single.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

<!-- Breadcrumb Start -->

<div class="sg-breadcrumb">
    <div class="container">
        <ol class="breadcrumb justify-content-center">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Main page</a></li>
            <li class="breadcrumb-item"><a href="{% url 'store:brands' %}">All Brands</a></li>
            <li class="breadcrumb-item"><a href="">{{ brand.title }}</a></li>
        </ol>
    </div>
</div><!-- /.sg-breadcrumb -->
<hr>
<div class="container">
    <div class="row">

        <!-- Post Image Start -->
        <div class="col-md-3">
            <div class="about-fixed">
                <div class="my-pic">
                    <img src="{{ brand.image.url }}" alt="{{ brand.title }}" class="img-fluid">
                </div>

            </div>
        </div>
        <!-- Post Image End -->

        <!-- Blog Post Start -->
        <div class="col-md-9">
            <div class="col-md-12 page-body">
                <div class="row">

                    <div class="col-md-12 content-page">
                        <div class="col-md-12 blog-post">

                            <!-- Post Headline Start -->
                            <div class="post-title">
                                <h1 class="text-dark text-uppercase">{{ brand.title }}</h1>
                            </div>
                            <!-- Post Headline End -->


                            <p>{{ brand.description|safe }}</p>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br/>
{% endblock %}

templates/store/brands.html
{% extends 'main.html' %}


{% load static %}

{% block content %}

<section class="sg-blog-section pt-0">
            <div class="container">
                <div class="sa-box">
                    <div class="title justify-content-between">
                        <h1>All categories</h1>
                    </div>
                    <div class="row">
                        {% for brand in brands %}
                            <div class="col-md-6 col-lg-3">
                                <div class="post">
                                    <div class="entry-header">
                                        <div class="entry-thumbnail">
                                            <a href="{% url 'store:brand_detail' slug=brand.slug %}"><img src="{{ brand.image.url }}" alt="Image" class="img-fluid"></a>
                                        </div>
                                        <div class="entry-content">
                                            <h2 class="entry-title"><a href="{% url 'store:brand_detail' slug=brand.slug %}">{{ brand.title }}</a></h2>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}


                    </div><!-- /.row -->
                </div><!-- /.sa-box -->
            </div><!-- /.container -->
        </section><!-- /.sg-blog-section -->

{% endblock %}

templates/store/checkout.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
<div class="container">
	<div class="sg-breadcrumb">
			<ol class="breadcrumb justify-content-center">
					<li class="breadcrumb-item"><a href="{% url 'cart:cart' %}">View Cart</a></li>
					<li class="breadcrumb-item"><a href="{% url 'cart:checkout' %}">Check Out</a></li>
					<li class="breadcrumb-item">Confirm Order</li>
			</ol>
	</div><!-- /.sg-breadcrumb -->
<!-- ============================ COMPONENT 1 ================================= -->

<div class="row">
	<aside class="col-lg-6">
<div class="card">
  <div class="card-body">
    <h4 class="card-title mb-4">Billing Address</h4>
    <form action="{% url 'orders:place_order' %}" method="POST">
      {% csrf_token %}
      <div class="form-row">
        <div class="col form-group">
          <input type="text" name="first_name" class="form-control" placeholder="First Name" required="required">
        </div>
        <div class="col form-group">
          <input type="text" name="last_name" placeholder="Last Name" class="form-control" required>
        </div>
      </div>
      <div class="form-row">
        <div class="col form-group">
          <input type="email" name="email" placeholder="Email" class="form-control" required>
        </div>
        <div class="col form-group">
          <input type="text" name="phone" placeholder="Phone Number" class="form-control" required>
        </div>
      </div>
      <div class="form-row">
        <div class="col form-group">
          <input type="text" name="address_line_1" placeholder="Address Line 1" class="form-control" required>
        </div>
        <div class="col form-group">
          <input type="text" name="address_line_2" placeholder="Address Line 2" class="form-control">
        </div>
      </div>
      <div class="form-row">
        <div class="col form-group">
          <input type="text" name="city" placeholder="City" class="form-control" required>
        </div>
        <div class="col form-group">
          <input type="text" name="state" placeholder="State" class="form-control" required>
        </div>
        <div class="col form-group">
          <input type="text" name="country" placeholder="Country" class="form-control" required>
        </div>
        </div>
        <div class="form-row">
          <textarea name="order_note" rows="2" placeholder="Order Note" class="form-control"></textarea>
        </div>
      <button type="submit" name="submit" class="btn btn-primary btn-block mt-4">Place Order</button>
      </form>
  </div>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-6">

		<div class="card">
		<div class="card-body">

      <h4 class="card-title mb-4">Order details</h4>
          <div class="p-30 mb-5">
              <div class="border-bottom">
                  <h5 class="mb-3">Product:</h5>
                  {% for cart_item in cart_items %}
                      <hr>
                      <div class="d-flex justify-content-between">
                          <p>Product: <strong>{{ cart_item.product.name }}</strong><br> Bags in case: <strong>{{ cart_item.product.bags_in_case }}</strong><br> Price: <strong>{{ cart_item.product.price }} $</strong><br> Quantity: <strong>{{ cart_item.quantity }} qty</strong></p>
                          <p>{{ cart_item.item_total }} $</p>
                      </div>
                  {% endfor %}
              </div>

              <div class="pt-2">
                  <div class="d-flex justify-content-between mt-2">
                      <h5>Total:</h5>
                      <h5>{{ total }} $</h5>
                  </div>
              </div>
          </div>

			<a href="{% url 'store:all_product_list' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->


</aside> <!-- col.// -->


</div> <!-- row.// -->

<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/store/filter_brand.html
{% load static %}

<!-- Manufacturer Start -->
<h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Фільтр по виробнику</span></h5>
<div class="bg-light p-4 mb-30">
    <form action="" method="get">
        <h4>Виробники:</h4>
        {% for manufacturer in manufacturers %}
            <div class="form-check d-flex align-items-center justify-content-between mb-3">
                <input class="form-check-input" type="checkbox" name="manufacturer_filter" value="{{ manufacturer.id }}" {% if manufacturer.id|slugify in manufacturer_filters %}checked{% endif %}>
                <label class="form-check-label" for="manufacturer_filter">{{ manufacturer.title }}</label>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Відфільтрувати</button>
    </form>
</div>
<!-- Manufacturer End -->

templates/store/filter_main.html
{% load static %}

<!-- Price Start -->
<h5 class="section-title position-relative text-uppercase mb-3">
  <span class="bg-warning pr-3 text-black">Filters:</span>
</h5>
<button type="button" class="btn btn-primary" id="resetFilters">Reset filters</button>
<div class="bg-light p-4 mb-30">
    <form action="" method="get">
        <h5>Price:</h5>
        {% for price_range in price_ranges %}
            <div class="form-check d-flex align-items-center justify-content-between mb-3">
                <input class="form-check-input" type="checkbox" name="price_filter" value="{{ price_range.id }}" {% if price_range.id|slugify in price_filters %}checked{% endif %}>
                <label class="form-check-label" for="price_filter">{{ price_range.name }}</label>
            </div>
        {% endfor %}



        <h5>Brands:</h5>
        {% for manufacturer in manufacturers %}
            <div class="form-check d-flex align-items-center justify-content-between mb-3">
                <input class="form-check-input" type="checkbox" name="manufacturer_filter" value="{{ manufacturer.id }}" {% if manufacturer.id|slugify in manufacturer_filters %}checked{% endif %}>
                <label class="form-check-label" for="manufacturer_filter">{{ manufacturer.title }}</label>
            </div>
        {% endfor %}



        <!-- <h5>Розміри:</h5>
        {% for size in sizes %}
            <div class="form-check d-flex align-items-center justify-content-between mb-3">
                <input class="form-check-input" type="checkbox" name="size_filter" value="{{ size.id }}" {% if size.id|slugify in size_filters %}checked{% endif %}>
                <label class="form-check-label" for="size_filter">{{ size.name }}</label>
            </div>
        {% endfor %} -->
        <button type="submit" class="btn btn-primary">Filter out</button>
    </form>
</div>
<!-- Price End -->

templates/store/filter_new.html
{% load static %}

<h3 class="mb-4 border-bottom pb-1">Filters</h3>

<!-- Форма для фильтров -->
<form id="filter-form"> <!-- Обернем фильтры в форму -->
  <!-- Фильтр по производителям -->
  <div class="card mb-4">
    <h6 class="card-header">Brands</h6>
    <div class="list-group list-group-flush">
      {% for brand in manufacturers_cat %}
      <li class="list-group-item">
        <input
          class="filter-checkbox"
          data-filter="manufacturer"
          value="{{ brand.id }}"
          type="checkbox"
          {% if brand.id in manufacturer_filters %}checked{% endif %}/>&nbsp;
        {{ brand.title }}
      </li>
      {% endfor %}
    </div>
  </div>

  <!-- Фильтр по весу -->
  <div class="card mb-4">
    <h6 class="card-header">Weight/Volume</h6>
    <div class="list-group list-group-flush">
      {% for weight in weights %}
      <li class="list-group-item">
        <input
          class="filter-checkbox"
          data-filter="weight"
          value="{{ weight }}"
          type="checkbox"
          {% if weight in weight_filters %}checked{% endif %}/>&nbsp;
        {{ weight }} OZ
      </li>
      {% endfor %}
    </div>
  </div>

  <!-- Фильтр по количеству пакетов в коробке -->
  <div class="card mb-4">
    <h6 class="card-header">Units per Case</h6>
    <div class="list-group list-group-flush">
      {% for bags in bags_in_case %}
      <li class="list-group-item">
        <input
          class="filter-checkbox"
          data-filter="bags"
          value="{{ bags }}"
          type="checkbox"
          {% if bags in bags_filters %}checked{% endif %}/>&nbsp;
        {{ bags }} ct
      </li>
      {% endfor %}
    </div>
  </div>

  <!-- Кнопка сброса всех фильтров -->
  <div class="text-center mt-4">
    <button type="button" id="reset-filters" class="btn btn-danger">Reset filters</button>
  </div>
</form>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const filterCheckboxes = document.querySelectorAll('.filter-checkbox');
    const resetButton = document.getElementById('reset-filters');

    // Обработчик изменения чекбоксов
    filterCheckboxes.forEach(checkbox => {
        checkbox.addEventListener('change', function () {
            let params = new URLSearchParams(window.location.search);
            let filterType = this.getAttribute('data-filter');
            let filterValue = this.value;

            // Обновляем параметры запроса
            if (this.checked) {
                if (params.has(filterType)) {
                    params.set(filterType, params.get(filterType) + ',' + filterValue);
                } else {
                    params.append(filterType, filterValue);
                }
            } else {
                let values = params.get(filterType).split(',');
                values = values.filter(val => val !== filterValue);
                if (values.length > 0) {
                    params.set(filterType, values.join(','));
                } else {
                    params.delete(filterType);
                }
            }

            // Перезагружаем страницу с новыми параметрами
            window.location.search = params.toString();
        });
    });

    // Обработчик события для кнопки сброса всех фильтров
    resetButton.addEventListener('click', function() {
        // Сбросить все чекбоксы в форме
        const checkboxes = document.querySelectorAll('input[type="checkbox"]');
        checkboxes.forEach(checkbox => {
            checkbox.checked = false;
        });

        // Отправить форму для возврата к изначальному списку товаров
        const form = document.getElementById('filter-form');
        form.submit();
    });
});
</script>

templates/store/promo_detail.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

<section class="products-section">
    <div class="container">
        <div class="sa-box">
            <div class="title justify-content-between">
                <h1>Special Offer</h1>
            </div>
            <ul class="products grid-6">
                {% for product in products %}
                    <li>
                        {% include 'product_card_in_list.html' %}
                    </li>
                {% endfor %}
            </ul>
        </div><!-- /.sa-box -->
    </div><!-- /.container -->
</section>

{% endblock %}

templates/store/promo_list.html
{% extends 'main.html' %}

{% load static %}

{% block content %}


<br>
<section class="campaign-section p-0">
    <div class="container">
        <div class="title justify-content-between">
            <h1>Special offer</h1>
        </div>
        <div class="row">
          {% for promo in promos %}
            <div class="col-md-6">
                <a href="{% url 'store:promo_detail' slug=promo.slug %}" class="add-banner">
                    <img src="{{ promo.image.url }}" alt="Image" class="img-fluid">
                </a>
            </div>
            {% endfor %}

        </div><!-- /.row -->
    </div><!-- /.container -->
</section><!-- /.campaign-section -->
{% endblock %}